# Generated by Django 3.0 on 2022-11-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO lettings_address SELECT * FROM oc_lettings_site_address"),
        migrations.RunSQL("INSERT INTO lettings_letting SELECT * FROM oc_lettings_site_letting")
    ]
