# Generated by Django 4.1.1 on 2023-01-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20221107_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'adresses'},
        ),
    ]
