version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  
jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout
      - run:
          name: launch docker
          command: docker-compose up
      - run:
          name: launch pytest
          command: pytest

workflows:
  deploy:
    jobs:
      - build_and_test