version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.1.4
  
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Launch pytest
          command: pytest    

workflows:
  deploy:
    jobs:
      - docker/publish:
        image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
        requires: build_and_test