version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run:
          name: launch pytest
          command: pytest

workflows:
  deploy:
    jobs:
      - build_and_test