version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Launch pytest
          command: pytest    

workflows:
  deploy:
    jobs:
      - build_and_test
      - docker/publish:
          image: $DOCKER_LOGIN/lettings
          tag: $CIRCLE_SHA1,latest
          requires: 
            - build_and_test
      - heroku/deploy-via-git:
          requires:
            - build_and_test